#!/usr/bin/env python3
"""Generate presentation-ready visuals for Graph RAG knowledge graphs.

Outputs:
1) overview_counts.png  -> node/edge type distributions
2) subgraph.png         -> local neighborhood around a focus gene
3) summary.json         -> machine-readable counts and focus metadata
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from typing import Dict, Iterable, Tuple

import matplotlib.pyplot as plt
import networkx as nx
from networkx.readwrite import json_graph


NODE_COLORS = {
    "gene": "#4C78A8",
    "layer": "#54A24B",
    "pattern": "#F58518",
    "unknown": "#9D9DA1",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Visualize Graph RAG knowledge graph artifacts")
    parser.add_argument(
        "--graph-path",
        default="rag_data/kg/code_kg.json",
        help="Path to graph JSON generated by CodeKnowledgeGraph.",
    )
    parser.add_argument(
        "--output-dir",
        default="plots/graph_rag",
        help="Directory to write visualization outputs.",
    )
    parser.add_argument(
        "--parent-gene-id",
        default=None,
        help="Optional gene_id to center the subgraph. If omitted, auto-select by highest accuracy.",
    )
    parser.add_argument("--radius", type=int, default=2, help="Neighborhood radius for focused subgraph.")
    parser.add_argument("--max-nodes", type=int, default=60, help="Maximum nodes shown in focused subgraph.")
    parser.add_argument(
        "--layout",
        choices=["spring", "kamada"],
        default="kamada",
        help="Layout algorithm for focused subgraph.",
    )
    parser.add_argument("--seed", type=int, default=42, help="Random seed for deterministic layouts.")
    parser.add_argument("--dpi", type=int, default=220, help="DPI for saved figures.")
    parser.add_argument(
        "--show-edge-labels",
        action="store_true",
        help="Render edge relation labels (can clutter large subgraphs).",
    )
    return parser.parse_args()


def load_graph(graph_path: Path) -> nx.MultiDiGraph:
    payload = json.loads(graph_path.read_text(encoding="utf-8"))
    graph = json_graph.node_link_graph(payload, edges="edges")
    if not isinstance(graph, nx.MultiDiGraph):
        graph = nx.MultiDiGraph(graph)
    return graph


def node_type_counts(graph: nx.MultiDiGraph) -> Counter:
    counts = Counter()
    for _, attrs in graph.nodes(data=True):
        counts[str(attrs.get("node_type", "unknown"))] += 1
    return counts


def edge_relation_counts(graph: nx.MultiDiGraph) -> Counter:
    counts = Counter()
    for _, _, attrs in graph.edges(data=True):
        counts[str(attrs.get("relation", "unknown"))] += 1
    return counts


def choose_focus_gene_node(graph: nx.MultiDiGraph, requested_gene_id: str | None) -> str | None:
    if requested_gene_id:
        candidate = f"gene:{requested_gene_id}"
        if candidate in graph:
            return candidate
        if requested_gene_id in graph:
            return requested_gene_id
        return None

    best_node = None
    best_acc = float("-inf")
    for node, attrs in graph.nodes(data=True):
        if attrs.get("node_type") != "gene":
            continue
        acc = attrs.get("accuracy")
        try:
            score = float(acc)
        except (TypeError, ValueError):
            score = float("-inf")
        if score > best_acc:
            best_acc = score
            best_node = node

    if best_node is not None:
        return best_node

    for node, attrs in graph.nodes(data=True):
        if attrs.get("node_type") == "gene":
            return node

    return None


def capped_neighborhood(
    graph: nx.MultiDiGraph,
    center_node: str,
    radius: int,
    max_nodes: int,
) -> nx.MultiDiGraph:
    undirected = graph.to_undirected(as_view=True)
    lengths = nx.single_source_shortest_path_length(undirected, center_node, cutoff=radius)

    ordered_nodes = sorted(lengths.items(), key=lambda item: (item[1], item[0]))
    selected_nodes = [node for node, _ in ordered_nodes[:max_nodes]]
    return graph.subgraph(selected_nodes).copy()


def node_label(node_id: str, attrs: Dict) -> str:
    node_type = attrs.get("node_type", "unknown")
    if node_type == "gene":
        return str(attrs.get("gene_id", node_id.replace("gene:", "")))
    if node_type == "layer":
        return str(attrs.get("layer_type", node_id.replace("layer:", "")))
    if node_type == "pattern":
        return str(attrs.get("pattern", node_id.replace("pattern:", "")))
    return node_id


def layout_positions(graph: nx.MultiDiGraph, layout: str, seed: int) -> Dict[str, Tuple[float, float]]:
    if layout == "spring":
        return nx.spring_layout(graph, seed=seed, k=1.1 / max(1, graph.number_of_nodes() ** 0.5))
    return nx.kamada_kawai_layout(graph)


def draw_overview(counts_nodes: Counter, counts_edges: Counter, output_path: Path, dpi: int) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    node_items = sorted(counts_nodes.items())
    edge_items = sorted(counts_edges.items())

    axes[0].bar(
        [k for k, _ in node_items],
        [v for _, v in node_items],
        color=[NODE_COLORS.get(k, NODE_COLORS["unknown"]) for k, _ in node_items],
    )
    axes[0].set_title("Node Type Counts")
    axes[0].set_ylabel("Count")
    axes[0].tick_params(axis="x", rotation=25)

    axes[1].bar([k for k, _ in edge_items], [v for _, v in edge_items], color="#7F7F7F")
    axes[1].set_title("Edge Relation Counts")
    axes[1].tick_params(axis="x", rotation=25)

    fig.suptitle("Graph RAG Knowledge Graph Overview", fontsize=14)
    fig.tight_layout()
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def draw_subgraph(
    graph: nx.MultiDiGraph,
    center_node: str,
    output_path: Path,
    layout: str,
    seed: int,
    dpi: int,
    show_edge_labels: bool,
) -> None:
    if graph.number_of_nodes() == 0:
        return

    positions = layout_positions(graph, layout, seed)
    labels = {node: node_label(node, attrs) for node, attrs in graph.nodes(data=True)}

    node_types = {node: graph.nodes[node].get("node_type", "unknown") for node in graph.nodes()}
    node_colors = [NODE_COLORS.get(node_types[node], NODE_COLORS["unknown"]) for node in graph.nodes()]
    node_sizes = [1100 if node == center_node else 550 for node in graph.nodes()]

    fig, ax = plt.subplots(figsize=(14, 10))
    nx.draw_networkx_nodes(
        graph,
        pos=positions,
        node_color=node_colors,
        node_size=node_sizes,
        edgecolors="#333333",
        linewidths=0.8,
        ax=ax,
        alpha=0.95,
    )

    nx.draw_networkx_edges(
        graph,
        pos=positions,
        ax=ax,
        arrows=True,
        arrowstyle="-|>",
        arrowsize=14,
        width=1.1,
        alpha=0.55,
        connectionstyle="arc3,rad=0.12",
    )

    nx.draw_networkx_labels(
        graph,
        pos=positions,
        labels=labels,
        font_size=8,
        font_weight="bold",
        ax=ax,
    )

    if show_edge_labels:
        edge_labels = {}
        for source, target, attrs in graph.edges(data=True):
            relation = str(attrs.get("relation", "unknown"))
            key = (source, target)
            if key in edge_labels:
                if relation not in edge_labels[key]:
                    edge_labels[key] += f",{relation}"
            else:
                edge_labels[key] = relation
        nx.draw_networkx_edge_labels(
            graph,
            positions,
            edge_labels=edge_labels,
            font_size=7,
            rotate=False,
            ax=ax,
            label_pos=0.55,
        )

    legend_handles = []
    for node_type, color in NODE_COLORS.items():
        if node_type == "unknown":
            continue
        handle = plt.Line2D(
            [0],
            [0],
            marker="o",
            color="w",
            markerfacecolor=color,
            markeredgecolor="#333333",
            markersize=9,
            label=node_type,
        )
        legend_handles.append(handle)

    ax.legend(handles=legend_handles, loc="upper left", title="Node types")
    center_label = node_label(center_node, graph.nodes[center_node])
    ax.set_title(f"Graph RAG Focused Subgraph (center: {center_label})", fontsize=13)
    ax.axis("off")
    fig.tight_layout()
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def write_summary(
    graph: nx.MultiDiGraph,
    focus_node: str | None,
    node_counts: Counter,
    edge_counts: Counter,
    output_path: Path,
) -> None:
    focus_payload = None
    if focus_node and focus_node in graph:
        attrs = dict(graph.nodes[focus_node])
        focus_payload = {
            "node_id": focus_node,
            "node_type": attrs.get("node_type"),
            "gene_id": attrs.get("gene_id"),
            "accuracy": attrs.get("accuracy"),
            "parameters": attrs.get("parameters"),
        }

    payload = {
        "nodes_total": graph.number_of_nodes(),
        "edges_total": graph.number_of_edges(),
        "node_type_counts": dict(node_counts),
        "edge_relation_counts": dict(edge_counts),
        "focus": focus_payload,
    }
    output_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def main() -> int:
    args = parse_args()

    graph_path = Path(args.graph_path)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if not graph_path.exists():
        print(f"[GraphRAG][Viz] Graph file not found: {graph_path}")
        print("[GraphRAG][Viz] Run Graph RAG retrieval first so code_kg.json is created.")
        return 1

    graph = load_graph(graph_path)
    if graph.number_of_nodes() == 0:
        print(f"[GraphRAG][Viz] Graph file is empty: {graph_path}")
        return 1

    node_counts = node_type_counts(graph)
    edge_counts = edge_relation_counts(graph)

    overview_path = output_dir / "overview_counts.png"
    draw_overview(node_counts, edge_counts, overview_path, dpi=args.dpi)

    focus_node = choose_focus_gene_node(graph, args.parent_gene_id)
    subgraph_path = output_dir / "subgraph.png"
    if focus_node is None:
        print("[GraphRAG][Viz] No gene nodes found; skipped subgraph rendering.")
    else:
        focused = capped_neighborhood(graph, focus_node, radius=args.radius, max_nodes=args.max_nodes)
        draw_subgraph(
            focused,
            center_node=focus_node,
            output_path=subgraph_path,
            layout=args.layout,
            seed=args.seed,
            dpi=args.dpi,
            show_edge_labels=args.show_edge_labels,
        )

    summary_path = output_dir / "summary.json"
    write_summary(graph, focus_node, node_counts, edge_counts, summary_path)

    print("[GraphRAG][Viz] Generated outputs:")
    print(f"  - {overview_path}")
    if focus_node is not None:
        print(f"  - {subgraph_path}")
    print(f"  - {summary_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
