import re

class OutputEvaluator:
    """
    Evaluates LLM outputs for code quality and format compliance.
    Currently checks for properly formatted Python code blocks.
    """
    
    @staticmethod
    def calculate_evaluation_score(generated_text: str) -> float:
        """
        Calculate evaluation score for LLM output.
        
        Args:
            generated_text: The text generated by the LLM
            
        Returns:
            float: Score between 0 and 1
                  - 1.0 if output contains Python code in markdown fences
                  - 0.0 otherwise
        """
        if not generated_text:
            return 0.0
        
        # Pattern to match ```python ... ``` code blocks
        python_code_pattern = r'```python\s+.*?```'
        
        # Check if the pattern exists in the generated text
        match = re.search(python_code_pattern, generated_text, re.DOTALL | re.IGNORECASE)
        
        return 1.0 if match else 0.0
    
    @staticmethod
    def extract_code_blocks(generated_text: str) -> list[str]:
        """
        Extract all Python code blocks from the generated text.
        Useful for future enhancements.
        
        Args:
            generated_text: The text generated by the LLM
            
        Returns:
            list[str]: List of extracted code blocks (without the fence markers)
        """
        pattern = r'```python\s+(.*?)```'
        matches = re.findall(pattern, generated_text, re.DOTALL | re.IGNORECASE)
        return [match.strip() for match in matches]
